import { config } from "dotenv";
config({ path: ".env.local" });

import { neon } from "@neondatabase/serverless";
import { PrismaNeon } from "@prisma/adapter-neon";
import { PrismaClient } from "@prisma/client";

const rawUrl = process.env.DATABASE_URL || "";
const connectionString = rawUrl
  .replace(/[&?]channel_binding=[^&]*/g, "")
  .replace(/\?&/, "?")
  .replace(/[?&]$/, "");

const sql = neon(connectionString);
const adapter = new PrismaNeon(sql);
const prisma = new PrismaClient({ adapter });

const ingredients = [
  { name: "eggs", category: "dairy" },
  { name: "milk", category: "dairy" },
  { name: "butter", category: "dairy" },
  { name: "heavy cream", category: "dairy" },
  { name: "cheddar cheese", category: "dairy" },
  { name: "parmesan cheese", category: "dairy" },
  { name: "mozzarella cheese", category: "dairy" },
  { name: "cream cheese", category: "dairy" },
  { name: "yogurt", category: "dairy" },
  { name: "sour cream", category: "dairy" },
  { name: "chicken breast", category: "protein" },
  { name: "chicken thighs", category: "protein" },
  { name: "ground beef", category: "protein" },
  { name: "salmon fillet", category: "protein" },
  { name: "shrimp", category: "protein" },
  { name: "bacon", category: "protein" },
  { name: "pork tenderloin", category: "protein" },
  { name: "ground turkey", category: "protein" },
  { name: "tuna", category: "protein" },
  { name: "tofu", category: "legumes" },
  { name: "onion", category: "produce" },
  { name: "garlic", category: "produce" },
  { name: "tomato", category: "produce" },
  { name: "bell pepper", category: "produce" },
  { name: "spinach", category: "produce" },
  { name: "broccoli", category: "produce" },
  { name: "carrot", category: "produce" },
  { name: "celery", category: "produce" },
  { name: "mushroom", category: "produce" },
  { name: "zucchini", category: "produce" },
  { name: "avocado", category: "produce" },
  { name: "lemon", category: "produce" },
  { name: "lime", category: "produce" },
  { name: "ginger", category: "produce" },
  { name: "cucumber", category: "produce" },
  { name: "potato", category: "produce" },
  { name: "sweet potato", category: "produce" },
  { name: "kale", category: "produce" },
  { name: "cherry tomatoes", category: "produce" },
  { name: "jalapeño", category: "produce" },
  { name: "rice", category: "grains" },
  { name: "pasta", category: "grains" },
  { name: "bread", category: "grains" },
  { name: "flour", category: "grains" },
  { name: "oats", category: "grains" },
  { name: "panko breadcrumbs", category: "grains" },
  { name: "tortilla", category: "grains" },
  { name: "noodles", category: "grains" },
  { name: "pita bread", category: "grains" },
  { name: "olive oil", category: "condiments" },
  { name: "vegetable oil", category: "condiments" },
  { name: "soy sauce", category: "condiments" },
  { name: "hot sauce", category: "condiments" },
  { name: "worcestershire sauce", category: "condiments" },
  { name: "dijon mustard", category: "condiments" },
  { name: "honey", category: "condiments" },
  { name: "vinegar", category: "condiments" },
  { name: "sesame oil", category: "condiments" },
  { name: "tomato sauce", category: "condiments" },
  { name: "coconut milk", category: "condiments" },
  { name: "salt", category: "spice" },
  { name: "black pepper", category: "spice" },
  { name: "cumin", category: "spice" },
  { name: "paprika", category: "spice" },
  { name: "oregano", category: "spice" },
  { name: "basil", category: "spice" },
  { name: "thyme", category: "spice" },
  { name: "cinnamon", category: "spice" },
  { name: "curry powder", category: "spice" },
  { name: "chili powder", category: "spice" },
  { name: "turmeric", category: "spice" },
  { name: "red pepper flakes", category: "spice" },
  { name: "garlic powder", category: "spice" },
  { name: "smoked paprika", category: "spice" },
  { name: "chickpeas", category: "legumes" },
  { name: "black beans", category: "legumes" },
  { name: "lentils", category: "legumes" },
  { name: "peanut butter", category: "condiments" },
  { name: "tahini", category: "condiments" },
  { name: "capers", category: "condiments" },
  { name: "sugar", category: "spice" },
  { name: "brown sugar", category: "spice" },
  { name: "baking powder", category: "spice" },
  { name: "vanilla extract", category: "spice" },
  { name: "cornstarch", category: "spice" },
  { name: "chicken broth", category: "condiments" },
  { name: "vegetable broth", category: "condiments" },
  { name: "white wine", category: "condiments" },
  { name: "beef broth", category: "condiments" },
];

const recipes = [
  {
    title: "Classic Spaghetti Carbonara",
    description: "Creamy Roman pasta with crispy bacon, eggs, and parmesan.",
    cuisine: "italian",
    mealType: "dinner",
    cookTimeMinutes: 25,
    servings: 4,
    dietaryTags: [],
    instructions: [
      { step_number: 1, text: "Cook pasta in salted boiling water until al dente. Reserve 1 cup pasta water." },
      { step_number: 2, text: "Fry bacon in a large pan until crispy. Remove from heat." },
      { step_number: 3, text: "Whisk eggs and grated parmesan together in a bowl." },
      { step_number: 4, text: "Add hot drained pasta to the bacon pan. Off heat, add egg mixture and toss quickly, adding pasta water to loosen." },
      { step_number: 5, text: "Season generously with black pepper and serve immediately." },
    ],
    ingredients: [
      { name: "pasta", quantity: "400g", isOptional: false },
      { name: "bacon", quantity: "150g", isOptional: false },
      { name: "eggs", quantity: "4 large", isOptional: false },
      { name: "parmesan cheese", quantity: "100g", isOptional: false },
      { name: "black pepper", quantity: "to taste", isOptional: false },
      { name: "salt", quantity: "to taste", isOptional: false },
    ],
  },
  {
    title: "Chicken Stir Fry",
    description: "Quick and healthy Asian-style stir fry with colorful vegetables.",
    cuisine: "asian",
    mealType: "dinner",
    cookTimeMinutes: 20,
    servings: 4,
    dietaryTags: ["dairy-free"],
    instructions: [
      { step_number: 1, text: "Slice chicken breast into thin strips. Season with salt and pepper." },
      { step_number: 2, text: "Heat oil in a wok over high heat. Cook chicken until golden, about 5 minutes. Remove and set aside." },
      { step_number: 3, text: "Add vegetables to the wok and stir fry for 3-4 minutes." },
      { step_number: 4, text: "Return chicken to the wok. Add soy sauce, garlic, and ginger. Toss to combine." },
      { step_number: 5, text: "Serve over steamed rice." },
    ],
    ingredients: [
      { name: "chicken breast", quantity: "500g", isOptional: false },
      { name: "broccoli", quantity: "1 head", isOptional: false },
      { name: "bell pepper", quantity: "2", isOptional: false },
      { name: "carrot", quantity: "2", isOptional: false },
      { name: "garlic", quantity: "3 cloves", isOptional: false },
      { name: "ginger", quantity: "1 inch", isOptional: false },
      { name: "soy sauce", quantity: "3 tbsp", isOptional: false },
      { name: "vegetable oil", quantity: "2 tbsp", isOptional: false },
      { name: "rice", quantity: "2 cups", isOptional: false },
      { name: "sesame oil", quantity: "1 tsp", isOptional: true },
    ],
  },
  {
    title: "Avocado Toast with Eggs",
    description: "Simple and nutritious breakfast with creamy avocado and perfectly cooked eggs.",
    cuisine: "american",
    mealType: "breakfast",
    cookTimeMinutes: 10,
    servings: 2,
    dietaryTags: ["vegetarian"],
    instructions: [
      { step_number: 1, text: "Toast bread slices until golden." },
      { step_number: 2, text: "Mash avocado with lemon juice, salt, and red pepper flakes." },
      { step_number: 3, text: "Fry or poach eggs to your liking." },
      { step_number: 4, text: "Spread avocado on toast and top with egg. Season and serve." },
    ],
    ingredients: [
      { name: "bread", quantity: "2 slices", isOptional: false },
      { name: "avocado", quantity: "1", isOptional: false },
      { name: "eggs", quantity: "2", isOptional: false },
      { name: "lemon", quantity: "1/2", isOptional: false },
      { name: "red pepper flakes", quantity: "pinch", isOptional: true },
      { name: "salt", quantity: "to taste", isOptional: false },
    ],
  },
  {
    title: "Butter Chicken",
    description: "Aromatic Indian curry with tender chicken in a rich tomato-cream sauce.",
    cuisine: "indian",
    mealType: "dinner",
    cookTimeMinutes: 45,
    servings: 4,
    dietaryTags: ["gluten-free"],
    instructions: [
      { step_number: 1, text: "Marinate chicken in yogurt, turmeric, and spices for 30 minutes." },
      { step_number: 2, text: "Cook onion, garlic, and ginger in butter until soft." },
      { step_number: 3, text: "Add tomato sauce, curry powder, and garam masala. Simmer 10 minutes." },
      { step_number: 4, text: "Add marinated chicken and cook through, about 15 minutes." },
      { step_number: 5, text: "Stir in heavy cream. Simmer 5 more minutes. Serve with rice." },
    ],
    ingredients: [
      { name: "chicken thighs", quantity: "700g", isOptional: false },
      { name: "yogurt", quantity: "1/2 cup", isOptional: false },
      { name: "tomato sauce", quantity: "400ml", isOptional: false },
      { name: "heavy cream", quantity: "1/2 cup", isOptional: false },
      { name: "butter", quantity: "3 tbsp", isOptional: false },
      { name: "onion", quantity: "1 large", isOptional: false },
      { name: "garlic", quantity: "4 cloves", isOptional: false },
      { name: "ginger", quantity: "1 inch", isOptional: false },
      { name: "curry powder", quantity: "2 tbsp", isOptional: false },
      { name: "turmeric", quantity: "1 tsp", isOptional: false },
      { name: "rice", quantity: "2 cups", isOptional: true },
    ],
  },
  {
    title: "Veggie Omelette",
    description: "Fluffy egg omelette packed with fresh vegetables and melted cheese.",
    cuisine: "american",
    mealType: "breakfast",
    cookTimeMinutes: 12,
    servings: 1,
    dietaryTags: ["vegetarian", "gluten-free"],
    instructions: [
      { step_number: 1, text: "Whisk 3 eggs with salt and pepper." },
      { step_number: 2, text: "Sauté diced vegetables in butter for 2 minutes." },
      { step_number: 3, text: "Pour eggs over vegetables. Cook on medium-low, lifting edges to let raw egg flow underneath." },
      { step_number: 4, text: "Add cheese and fold omelette in half. Slide onto plate." },
    ],
    ingredients: [
      { name: "eggs", quantity: "3", isOptional: false },
      { name: "bell pepper", quantity: "1/2", isOptional: false },
      { name: "mushroom", quantity: "4", isOptional: false },
      { name: "spinach", quantity: "handful", isOptional: false },
      { name: "cheddar cheese", quantity: "30g", isOptional: false },
      { name: "butter", quantity: "1 tbsp", isOptional: false },
      { name: "salt", quantity: "to taste", isOptional: false },
      { name: "black pepper", quantity: "to taste", isOptional: false },
    ],
  },
  {
    title: "Classic Caesar Salad",
    description: "Crisp romaine lettuce with creamy Caesar dressing and parmesan croutons.",
    cuisine: "american",
    mealType: "lunch",
    cookTimeMinutes: 15,
    servings: 4,
    dietaryTags: [],
    instructions: [
      { step_number: 1, text: "Make croutons: toss bread cubes with olive oil and toast in oven at 180°C until golden." },
      { step_number: 2, text: "Whisk together garlic, lemon juice, dijon mustard, worcestershire sauce, and olive oil." },
      { step_number: 3, text: "Toss romaine with dressing and top with parmesan and croutons." },
    ],
    ingredients: [
      { name: "bread", quantity: "4 slices", isOptional: false },
      { name: "parmesan cheese", quantity: "50g", isOptional: false },
      { name: "lemon", quantity: "1", isOptional: false },
      { name: "garlic", quantity: "2 cloves", isOptional: false },
      { name: "dijon mustard", quantity: "1 tsp", isOptional: false },
      { name: "worcestershire sauce", quantity: "1 tsp", isOptional: false },
      { name: "olive oil", quantity: "4 tbsp", isOptional: false },
      { name: "eggs", quantity: "1", isOptional: true },
    ],
  },
  {
    title: "Beef Tacos",
    description: "Seasoned ground beef tacos with fresh toppings and soft tortillas.",
    cuisine: "mexican",
    mealType: "dinner",
    cookTimeMinutes: 25,
    servings: 4,
    dietaryTags: [],
    instructions: [
      { step_number: 1, text: "Brown ground beef in a pan. Drain excess fat." },
      { step_number: 2, text: "Add cumin, chili powder, garlic powder, salt, and a splash of water. Simmer 5 minutes." },
      { step_number: 3, text: "Warm tortillas in a dry pan." },
      { step_number: 4, text: "Serve beef in tortillas with avocado, tomato, and sour cream." },
    ],
    ingredients: [
      { name: "ground beef", quantity: "500g", isOptional: false },
      { name: "tortilla", quantity: "8", isOptional: false },
      { name: "cumin", quantity: "2 tsp", isOptional: false },
      { name: "chili powder", quantity: "1 tsp", isOptional: false },
      { name: "garlic powder", quantity: "1 tsp", isOptional: false },
      { name: "avocado", quantity: "2", isOptional: false },
      { name: "tomato", quantity: "2", isOptional: false },
      { name: "sour cream", quantity: "1/2 cup", isOptional: true },
      { name: "lime", quantity: "1", isOptional: true },
    ],
  },
  {
    title: "Lemon Garlic Salmon",
    description: "Pan-seared salmon with bright lemon-garlic butter sauce.",
    cuisine: "mediterranean",
    mealType: "dinner",
    cookTimeMinutes: 20,
    servings: 2,
    dietaryTags: ["gluten-free", "dairy-free"],
    instructions: [
      { step_number: 1, text: "Pat salmon dry. Season with salt, pepper, and paprika." },
      { step_number: 2, text: "Heat olive oil in a pan over high heat. Cook salmon skin-side down 4 minutes, flip, cook 3 more." },
      { step_number: 3, text: "Remove salmon. Add butter, garlic, and lemon juice to pan. Swirl to combine." },
      { step_number: 4, text: "Pour sauce over salmon and garnish with fresh herbs." },
    ],
    ingredients: [
      { name: "salmon fillet", quantity: "2 fillets", isOptional: false },
      { name: "lemon", quantity: "1", isOptional: false },
      { name: "garlic", quantity: "3 cloves", isOptional: false },
      { name: "butter", quantity: "2 tbsp", isOptional: false },
      { name: "olive oil", quantity: "2 tbsp", isOptional: false },
      { name: "paprika", quantity: "1 tsp", isOptional: false },
      { name: "salt", quantity: "to taste", isOptional: false },
      { name: "black pepper", quantity: "to taste", isOptional: false },
    ],
  },
  {
    title: "Overnight Oats",
    description: "No-cook creamy oats prepared the night before — perfect for busy mornings.",
    cuisine: "american",
    mealType: "breakfast",
    cookTimeMinutes: 5,
    servings: 2,
    dietaryTags: ["vegetarian", "vegan"],
    instructions: [
      { step_number: 1, text: "Combine oats, milk, yogurt, and honey in a jar." },
      { step_number: 2, text: "Stir well, seal, and refrigerate overnight." },
      { step_number: 3, text: "In the morning, stir and top with fresh fruit or nut butter." },
    ],
    ingredients: [
      { name: "oats", quantity: "1 cup", isOptional: false },
      { name: "milk", quantity: "1 cup", isOptional: false },
      { name: "yogurt", quantity: "1/4 cup", isOptional: true },
      { name: "honey", quantity: "1 tbsp", isOptional: true },
      { name: "peanut butter", quantity: "2 tbsp", isOptional: true },
    ],
  },
  {
    title: "Mushroom Risotto",
    description: "Creamy Italian arborio rice with earthy mushrooms and aged parmesan.",
    cuisine: "italian",
    mealType: "dinner",
    cookTimeMinutes: 40,
    servings: 4,
    dietaryTags: ["vegetarian", "gluten-free"],
    instructions: [
      { step_number: 1, text: "Sauté onion and garlic in butter until soft." },
      { step_number: 2, text: "Add mushrooms and cook until they release moisture." },
      { step_number: 3, text: "Add rice and toast for 2 minutes. Add white wine and stir until absorbed." },
      { step_number: 4, text: "Add warm broth one ladle at a time, stirring constantly until absorbed each time. Continue 20-25 minutes until creamy." },
      { step_number: 5, text: "Stir in butter and parmesan. Season and serve." },
    ],
    ingredients: [
      { name: "rice", quantity: "300g", isOptional: false },
      { name: "mushroom", quantity: "400g", isOptional: false },
      { name: "onion", quantity: "1", isOptional: false },
      { name: "garlic", quantity: "3 cloves", isOptional: false },
      { name: "butter", quantity: "4 tbsp", isOptional: false },
      { name: "parmesan cheese", quantity: "100g", isOptional: false },
      { name: "white wine", quantity: "100ml", isOptional: false },
      { name: "chicken broth", quantity: "1.2L", isOptional: false },
    ],
  },
  {
    title: "Shrimp Fried Rice",
    description: "Quick and flavorful fried rice with shrimp, eggs, and vegetables.",
    cuisine: "asian",
    mealType: "dinner",
    cookTimeMinutes: 20,
    servings: 4,
    dietaryTags: ["dairy-free"],
    instructions: [
      { step_number: 1, text: "Cook rice the day before and refrigerate (or use leftover rice)." },
      { step_number: 2, text: "Heat oil in a wok. Add shrimp and cook until pink. Remove." },
      { step_number: 3, text: "Scramble eggs in the wok. Add vegetables and cook 2 minutes." },
      { step_number: 4, text: "Add cold rice and stir fry over high heat. Add soy sauce and shrimp. Toss to combine." },
    ],
    ingredients: [
      { name: "shrimp", quantity: "300g", isOptional: false },
      { name: "rice", quantity: "3 cups cooked", isOptional: false },
      { name: "eggs", quantity: "3", isOptional: false },
      { name: "carrot", quantity: "1", isOptional: false },
      { name: "onion", quantity: "1", isOptional: false },
      { name: "garlic", quantity: "3 cloves", isOptional: false },
      { name: "soy sauce", quantity: "3 tbsp", isOptional: false },
      { name: "vegetable oil", quantity: "3 tbsp", isOptional: false },
      { name: "sesame oil", quantity: "1 tsp", isOptional: true },
    ],
  },
  {
    title: "Chickpea Curry",
    description: "Hearty vegan curry with creamy coconut milk and aromatic spices.",
    cuisine: "indian",
    mealType: "dinner",
    cookTimeMinutes: 30,
    servings: 4,
    dietaryTags: ["vegan", "vegetarian", "gluten-free"],
    instructions: [
      { step_number: 1, text: "Sauté onion, garlic, and ginger until golden." },
      { step_number: 2, text: "Add curry powder, turmeric, and cumin. Cook 1 minute." },
      { step_number: 3, text: "Add diced tomatoes and cook 5 minutes." },
      { step_number: 4, text: "Add chickpeas and coconut milk. Simmer 15 minutes." },
      { step_number: 5, text: "Season with salt and garnish with fresh cilantro." },
    ],
    ingredients: [
      { name: "chickpeas", quantity: "2 cans", isOptional: false },
      { name: "coconut milk", quantity: "400ml", isOptional: false },
      { name: "tomato", quantity: "2", isOptional: false },
      { name: "onion", quantity: "1", isOptional: false },
      { name: "garlic", quantity: "4 cloves", isOptional: false },
      { name: "ginger", quantity: "1 inch", isOptional: false },
      { name: "curry powder", quantity: "2 tbsp", isOptional: false },
      { name: "turmeric", quantity: "1 tsp", isOptional: false },
      { name: "cumin", quantity: "1 tsp", isOptional: false },
    ],
  },
  {
    title: "BLT Sandwich",
    description: "Classic bacon, lettuce, and tomato sandwich with mayo.",
    cuisine: "american",
    mealType: "lunch",
    cookTimeMinutes: 10,
    servings: 2,
    dietaryTags: [],
    instructions: [
      { step_number: 1, text: "Cook bacon until crispy." },
      { step_number: 2, text: "Toast bread slices." },
      { step_number: 3, text: "Spread mayo on toast. Layer bacon, sliced tomato, and lettuce." },
      { step_number: 4, text: "Season with salt and pepper. Close and serve." },
    ],
    ingredients: [
      { name: "bacon", quantity: "6 slices", isOptional: false },
      { name: "bread", quantity: "4 slices", isOptional: false },
      { name: "tomato", quantity: "1", isOptional: false },
    ],
  },
  {
    title: "Greek Salad",
    description: "Refreshing Mediterranean salad with feta, olives, and crisp vegetables.",
    cuisine: "mediterranean",
    mealType: "lunch",
    cookTimeMinutes: 10,
    servings: 4,
    dietaryTags: ["vegetarian", "gluten-free"],
    instructions: [
      { step_number: 1, text: "Chop cucumber, tomatoes, bell pepper, and red onion." },
      { step_number: 2, text: "Combine in a bowl. Top with feta cheese." },
      { step_number: 3, text: "Drizzle with olive oil and lemon juice. Season with oregano, salt, and pepper." },
    ],
    ingredients: [
      { name: "cucumber", quantity: "1", isOptional: false },
      { name: "tomato", quantity: "3", isOptional: false },
      { name: "bell pepper", quantity: "1", isOptional: false },
      { name: "onion", quantity: "1/2 red", isOptional: false },
      { name: "mozzarella cheese", quantity: "200g", isOptional: false },
      { name: "olive oil", quantity: "4 tbsp", isOptional: false },
      { name: "lemon", quantity: "1", isOptional: false },
      { name: "oregano", quantity: "1 tsp", isOptional: false },
    ],
  },
  {
    title: "Creamy Tomato Soup",
    description: "Velvety smooth tomato soup with a touch of cream and fresh basil.",
    cuisine: "american",
    mealType: "lunch",
    cookTimeMinutes: 30,
    servings: 4,
    dietaryTags: ["vegetarian", "gluten-free"],
    instructions: [
      { step_number: 1, text: "Sauté onion and garlic in butter until soft." },
      { step_number: 2, text: "Add diced tomatoes and chicken broth. Simmer 20 minutes." },
      { step_number: 3, text: "Blend until smooth. Return to heat." },
      { step_number: 4, text: "Stir in cream and season. Top with fresh basil." },
    ],
    ingredients: [
      { name: "tomato", quantity: "6 large", isOptional: false },
      { name: "onion", quantity: "1", isOptional: false },
      { name: "garlic", quantity: "3 cloves", isOptional: false },
      { name: "butter", quantity: "2 tbsp", isOptional: false },
      { name: "chicken broth", quantity: "500ml", isOptional: false },
      { name: "heavy cream", quantity: "1/4 cup", isOptional: false },
      { name: "basil", quantity: "fresh", isOptional: true },
    ],
  },
  {
    title: "Grilled Cheese",
    description: "Golden crispy grilled cheese sandwich with gooey melted cheese.",
    cuisine: "american",
    mealType: "lunch",
    cookTimeMinutes: 8,
    servings: 2,
    dietaryTags: ["vegetarian"],
    instructions: [
      { step_number: 1, text: "Butter one side of each bread slice." },
      { step_number: 2, text: "Place cheese between bread slices, buttered sides out." },
      { step_number: 3, text: "Cook in a pan over medium heat 3-4 minutes per side until golden and cheese melts." },
    ],
    ingredients: [
      { name: "bread", quantity: "4 slices", isOptional: false },
      { name: "cheddar cheese", quantity: "100g", isOptional: false },
      { name: "butter", quantity: "2 tbsp", isOptional: false },
    ],
  },
  {
    title: "Honey Garlic Chicken",
    description: "Sticky, caramelized chicken with a sweet-savory honey garlic glaze.",
    cuisine: "asian",
    mealType: "dinner",
    cookTimeMinutes: 30,
    servings: 4,
    dietaryTags: ["dairy-free", "gluten-free"],
    instructions: [
      { step_number: 1, text: "Season chicken thighs with salt and pepper." },
      { step_number: 2, text: "Sear chicken skin-side down in oil until golden, 5-6 minutes. Flip." },
      { step_number: 3, text: "Mix honey, soy sauce, garlic, and vinegar. Pour over chicken." },
      { step_number: 4, text: "Bake at 200°C for 20 minutes, basting halfway through." },
    ],
    ingredients: [
      { name: "chicken thighs", quantity: "800g", isOptional: false },
      { name: "honey", quantity: "3 tbsp", isOptional: false },
      { name: "soy sauce", quantity: "3 tbsp", isOptional: false },
      { name: "garlic", quantity: "5 cloves", isOptional: false },
      { name: "vinegar", quantity: "1 tbsp", isOptional: false },
      { name: "vegetable oil", quantity: "2 tbsp", isOptional: false },
    ],
  },
  {
    title: "Shakshuka",
    description: "Poached eggs in a spiced tomato pepper sauce — great for breakfast or dinner.",
    cuisine: "mediterranean",
    mealType: "breakfast",
    cookTimeMinutes: 25,
    servings: 4,
    dietaryTags: ["vegetarian", "gluten-free"],
    instructions: [
      { step_number: 1, text: "Sauté onion and bell pepper in olive oil until soft." },
      { step_number: 2, text: "Add garlic, cumin, paprika, and chili powder. Cook 1 minute." },
      { step_number: 3, text: "Add tomatoes and simmer 10 minutes until thickened." },
      { step_number: 4, text: "Make wells in the sauce and crack eggs in. Cover and cook until whites are set, 5-7 minutes." },
      { step_number: 5, text: "Serve with bread for dipping." },
    ],
    ingredients: [
      { name: "eggs", quantity: "6", isOptional: false },
      { name: "tomato", quantity: "4", isOptional: false },
      { name: "bell pepper", quantity: "2", isOptional: false },
      { name: "onion", quantity: "1", isOptional: false },
      { name: "garlic", quantity: "3 cloves", isOptional: false },
      { name: "olive oil", quantity: "3 tbsp", isOptional: false },
      { name: "cumin", quantity: "1 tsp", isOptional: false },
      { name: "paprika", quantity: "1 tsp", isOptional: false },
      { name: "chili powder", quantity: "1/2 tsp", isOptional: true },
      { name: "bread", quantity: "to serve", isOptional: true },
    ],
  },
  {
    title: "Pasta Primavera",
    description: "Light and fresh pasta loaded with seasonal vegetables in garlic olive oil.",
    cuisine: "italian",
    mealType: "dinner",
    cookTimeMinutes: 25,
    servings: 4,
    dietaryTags: ["vegetarian"],
    instructions: [
      { step_number: 1, text: "Cook pasta until al dente. Reserve pasta water." },
      { step_number: 2, text: "Sauté zucchini, cherry tomatoes, and garlic in olive oil." },
      { step_number: 3, text: "Add spinach and cook until wilted." },
      { step_number: 4, text: "Toss with pasta, pasta water, parmesan, and basil." },
    ],
    ingredients: [
      { name: "pasta", quantity: "400g", isOptional: false },
      { name: "zucchini", quantity: "2", isOptional: false },
      { name: "cherry tomatoes", quantity: "250g", isOptional: false },
      { name: "spinach", quantity: "100g", isOptional: false },
      { name: "garlic", quantity: "4 cloves", isOptional: false },
      { name: "olive oil", quantity: "4 tbsp", isOptional: false },
      { name: "parmesan cheese", quantity: "60g", isOptional: true },
      { name: "basil", quantity: "fresh", isOptional: true },
    ],
  },
  {
    title: "Turkey Burger",
    description: "Juicy ground turkey burgers with all the classic toppings.",
    cuisine: "american",
    mealType: "dinner",
    cookTimeMinutes: 20,
    servings: 4,
    dietaryTags: [],
    instructions: [
      { step_number: 1, text: "Mix ground turkey with garlic powder, salt, pepper, and worcestershire sauce. Form into 4 patties." },
      { step_number: 2, text: "Grill or pan fry 5-6 minutes per side until cooked through." },
      { step_number: 3, text: "Serve on bread with avocado, tomato, and your preferred condiments." },
    ],
    ingredients: [
      { name: "ground turkey", quantity: "600g", isOptional: false },
      { name: "bread", quantity: "4 buns", isOptional: false },
      { name: "avocado", quantity: "1", isOptional: true },
      { name: "tomato", quantity: "1", isOptional: true },
      { name: "garlic powder", quantity: "1 tsp", isOptional: false },
      { name: "worcestershire sauce", quantity: "1 tbsp", isOptional: false },
    ],
  },
  {
    title: "Lentil Soup",
    description: "Hearty, warming red lentil soup with cumin and lemon.",
    cuisine: "mediterranean",
    mealType: "lunch",
    cookTimeMinutes: 35,
    servings: 6,
    dietaryTags: ["vegan", "vegetarian", "gluten-free"],
    instructions: [
      { step_number: 1, text: "Sauté onion, garlic, and carrot in olive oil." },
      { step_number: 2, text: "Add lentils, vegetable broth, cumin, and turmeric." },
      { step_number: 3, text: "Simmer 25-30 minutes until lentils are soft." },
      { step_number: 4, text: "Blend partially for a creamy texture. Add lemon juice and season." },
    ],
    ingredients: [
      { name: "lentils", quantity: "300g", isOptional: false },
      { name: "onion", quantity: "1", isOptional: false },
      { name: "garlic", quantity: "3 cloves", isOptional: false },
      { name: "carrot", quantity: "2", isOptional: false },
      { name: "vegetable broth", quantity: "1.5L", isOptional: false },
      { name: "olive oil", quantity: "3 tbsp", isOptional: false },
      { name: "cumin", quantity: "2 tsp", isOptional: false },
      { name: "turmeric", quantity: "1 tsp", isOptional: false },
      { name: "lemon", quantity: "1", isOptional: false },
    ],
  },
  {
    title: "Pad Thai",
    description: "Classic Thai stir-fried noodles with tamarind, peanuts, and fresh lime.",
    cuisine: "asian",
    mealType: "dinner",
    cookTimeMinutes: 25,
    servings: 4,
    dietaryTags: ["dairy-free"],
    instructions: [
      { step_number: 1, text: "Soak rice noodles in hot water 20 minutes, drain." },
      { step_number: 2, text: "Heat oil in a wok. Cook shrimp until pink, push to side. Scramble eggs." },
      { step_number: 3, text: "Add noodles, soy sauce, and a pinch of sugar. Toss to combine." },
      { step_number: 4, text: "Serve topped with peanut butter thinned with water, lime, and bean sprouts." },
    ],
    ingredients: [
      { name: "noodles", quantity: "300g rice noodles", isOptional: false },
      { name: "shrimp", quantity: "300g", isOptional: false },
      { name: "eggs", quantity: "3", isOptional: false },
      { name: "soy sauce", quantity: "3 tbsp", isOptional: false },
      { name: "peanut butter", quantity: "2 tbsp", isOptional: false },
      { name: "lime", quantity: "2", isOptional: false },
      { name: "garlic", quantity: "3 cloves", isOptional: false },
      { name: "vegetable oil", quantity: "3 tbsp", isOptional: false },
      { name: "sugar", quantity: "1 tsp", isOptional: false },
    ],
  },
  {
    title: "Garlic Butter Shrimp Pasta",
    description: "Linguine tossed with succulent shrimp in a rich garlic butter sauce.",
    cuisine: "italian",
    mealType: "dinner",
    cookTimeMinutes: 20,
    servings: 4,
    dietaryTags: [],
    instructions: [
      { step_number: 1, text: "Cook pasta and reserve pasta water." },
      { step_number: 2, text: "Sauté garlic in butter until fragrant. Add shrimp and cook 3 minutes." },
      { step_number: 3, text: "Add lemon juice and red pepper flakes." },
      { step_number: 4, text: "Toss with pasta and pasta water. Finish with parmesan." },
    ],
    ingredients: [
      { name: "pasta", quantity: "400g", isOptional: false },
      { name: "shrimp", quantity: "400g", isOptional: false },
      { name: "butter", quantity: "4 tbsp", isOptional: false },
      { name: "garlic", quantity: "5 cloves", isOptional: false },
      { name: "lemon", quantity: "1", isOptional: false },
      { name: "red pepper flakes", quantity: "1/2 tsp", isOptional: false },
      { name: "parmesan cheese", quantity: "60g", isOptional: true },
    ],
  },
  {
    title: "Black Bean Tacos",
    description: "Easy vegetarian tacos with spiced black beans, avocado, and salsa.",
    cuisine: "mexican",
    mealType: "dinner",
    cookTimeMinutes: 15,
    servings: 4,
    dietaryTags: ["vegetarian", "vegan", "gluten-free"],
    instructions: [
      { step_number: 1, text: "Heat black beans with cumin, chili powder, and garlic." },
      { step_number: 2, text: "Warm tortillas." },
      { step_number: 3, text: "Fill with beans, sliced avocado, cherry tomatoes, and lime juice." },
    ],
    ingredients: [
      { name: "black beans", quantity: "2 cans", isOptional: false },
      { name: "tortilla", quantity: "8", isOptional: false },
      { name: "avocado", quantity: "2", isOptional: false },
      { name: "cherry tomatoes", quantity: "250g", isOptional: false },
      { name: "lime", quantity: "1", isOptional: false },
      { name: "cumin", quantity: "2 tsp", isOptional: false },
      { name: "chili powder", quantity: "1 tsp", isOptional: false },
    ],
  },
  {
    title: "Banana Pancakes",
    description: "Fluffy 2-ingredient banana pancakes — naturally sweet and gluten-free.",
    cuisine: "american",
    mealType: "breakfast",
    cookTimeMinutes: 15,
    servings: 2,
    dietaryTags: ["vegetarian", "gluten-free", "dairy-free"],
    instructions: [
      { step_number: 1, text: "Mash 2 ripe bananas with a fork until smooth." },
      { step_number: 2, text: "Mix in 2 eggs and a pinch of cinnamon." },
      { step_number: 3, text: "Cook in buttered pan over medium heat, 2 minutes per side." },
      { step_number: 4, text: "Serve with honey or maple syrup." },
    ],
    ingredients: [
      { name: "eggs", quantity: "2", isOptional: false },
      { name: "cinnamon", quantity: "1/2 tsp", isOptional: true },
      { name: "honey", quantity: "to serve", isOptional: true },
      { name: "butter", quantity: "1 tbsp", isOptional: false },
    ],
  },
  {
    title: "Sweet Potato Soup",
    description: "Velvety smooth sweet potato soup with coconut milk and warming spices.",
    cuisine: "american",
    mealType: "lunch",
    cookTimeMinutes: 35,
    servings: 4,
    dietaryTags: ["vegan", "vegetarian", "gluten-free"],
    instructions: [
      { step_number: 1, text: "Roast sweet potatoes at 200°C for 20 minutes." },
      { step_number: 2, text: "Sauté onion and garlic. Add ginger and curry powder." },
      { step_number: 3, text: "Add roasted sweet potato, vegetable broth, and coconut milk." },
      { step_number: 4, text: "Blend until smooth. Season and serve." },
    ],
    ingredients: [
      { name: "sweet potato", quantity: "600g", isOptional: false },
      { name: "coconut milk", quantity: "400ml", isOptional: false },
      { name: "vegetable broth", quantity: "500ml", isOptional: false },
      { name: "onion", quantity: "1", isOptional: false },
      { name: "garlic", quantity: "2 cloves", isOptional: false },
      { name: "ginger", quantity: "1 inch", isOptional: false },
      { name: "curry powder", quantity: "1.5 tsp", isOptional: false },
    ],
  },
  {
    title: "Pesto Pasta",
    description: "Vibrant basil pesto tossed with linguine and cherry tomatoes.",
    cuisine: "italian",
    mealType: "dinner",
    cookTimeMinutes: 20,
    servings: 4,
    dietaryTags: ["vegetarian"],
    instructions: [
      { step_number: 1, text: "Blend basil, parmesan, garlic, olive oil, and salt into pesto." },
      { step_number: 2, text: "Cook pasta until al dente. Reserve pasta water." },
      { step_number: 3, text: "Toss hot pasta with pesto, halved cherry tomatoes, and a splash of pasta water." },
    ],
    ingredients: [
      { name: "pasta", quantity: "400g", isOptional: false },
      { name: "basil", quantity: "large bunch", isOptional: false },
      { name: "parmesan cheese", quantity: "80g", isOptional: false },
      { name: "garlic", quantity: "2 cloves", isOptional: false },
      { name: "olive oil", quantity: "5 tbsp", isOptional: false },
      { name: "cherry tomatoes", quantity: "200g", isOptional: true },
    ],
  },
  {
    title: "Tofu Scramble",
    description: "Plant-based scrambled tofu with turmeric and vegetables for a protein-packed breakfast.",
    cuisine: "american",
    mealType: "breakfast",
    cookTimeMinutes: 15,
    servings: 2,
    dietaryTags: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
    instructions: [
      { step_number: 1, text: "Crumble firm tofu into a pan with oil." },
      { step_number: 2, text: "Add turmeric, garlic powder, salt, and nutritional yeast." },
      { step_number: 3, text: "Add diced bell pepper and spinach. Cook 5 minutes." },
      { step_number: 4, text: "Serve with toast or tortilla." },
    ],
    ingredients: [
      { name: "tofu", quantity: "400g firm", isOptional: false },
      { name: "bell pepper", quantity: "1", isOptional: false },
      { name: "spinach", quantity: "60g", isOptional: false },
      { name: "turmeric", quantity: "1 tsp", isOptional: false },
      { name: "garlic powder", quantity: "1 tsp", isOptional: false },
      { name: "olive oil", quantity: "2 tbsp", isOptional: false },
      { name: "salt", quantity: "to taste", isOptional: false },
    ],
  },
  {
    title: "Beef & Vegetable Stew",
    description: "Rich and hearty slow-cooked beef stew loaded with root vegetables.",
    cuisine: "american",
    mealType: "dinner",
    cookTimeMinutes: 90,
    servings: 6,
    dietaryTags: ["dairy-free", "gluten-free"],
    instructions: [
      { step_number: 1, text: "Brown beef cubes in batches in oil. Set aside." },
      { step_number: 2, text: "Sauté onion, celery, and garlic. Add tomato sauce and beef broth." },
      { step_number: 3, text: "Return beef. Add potato, carrot, and thyme." },
      { step_number: 4, text: "Simmer covered for 60-70 minutes until beef is tender." },
    ],
    ingredients: [
      { name: "ground beef", quantity: "800g cubes", isOptional: false },
      { name: "potato", quantity: "4", isOptional: false },
      { name: "carrot", quantity: "3", isOptional: false },
      { name: "celery", quantity: "3 stalks", isOptional: false },
      { name: "onion", quantity: "2", isOptional: false },
      { name: "garlic", quantity: "3 cloves", isOptional: false },
      { name: "beef broth", quantity: "1L", isOptional: false },
      { name: "tomato sauce", quantity: "400ml", isOptional: false },
      { name: "thyme", quantity: "2 sprigs", isOptional: false },
    ],
  },
  {
    title: "Hummus & Pita",
    description: "Creamy homemade hummus with warm pita bread and olive oil.",
    cuisine: "mediterranean",
    mealType: "snack",
    cookTimeMinutes: 10,
    servings: 6,
    dietaryTags: ["vegan", "vegetarian"],
    instructions: [
      { step_number: 1, text: "Blend chickpeas, tahini, lemon juice, garlic, and olive oil until smooth." },
      { step_number: 2, text: "Add water to reach desired consistency. Season with salt." },
      { step_number: 3, text: "Serve in a bowl, drizzle with olive oil, and sprinkle paprika." },
      { step_number: 4, text: "Warm pita and serve alongside." },
    ],
    ingredients: [
      { name: "chickpeas", quantity: "1 can", isOptional: false },
      { name: "tahini", quantity: "3 tbsp", isOptional: false },
      { name: "lemon", quantity: "1", isOptional: false },
      { name: "garlic", quantity: "2 cloves", isOptional: false },
      { name: "olive oil", quantity: "4 tbsp", isOptional: false },
      { name: "paprika", quantity: "1 tsp", isOptional: false },
      { name: "pita bread", quantity: "4", isOptional: false },
    ],
  },
  {
    title: "Kale Caesar Salad",
    description: "Hearty kale version of the Caesar salad with anchovy-free dressing.",
    cuisine: "american",
    mealType: "lunch",
    cookTimeMinutes: 15,
    servings: 4,
    dietaryTags: ["vegetarian"],
    instructions: [
      { step_number: 1, text: "Massage kale with a pinch of salt until slightly wilted." },
      { step_number: 2, text: "Whisk lemon juice, dijon mustard, garlic, olive oil, and parmesan for dressing." },
      { step_number: 3, text: "Toss kale with dressing. Top with croutons and extra parmesan." },
    ],
    ingredients: [
      { name: "kale", quantity: "1 bunch", isOptional: false },
      { name: "parmesan cheese", quantity: "60g", isOptional: false },
      { name: "lemon", quantity: "1", isOptional: false },
      { name: "garlic", quantity: "2 cloves", isOptional: false },
      { name: "dijon mustard", quantity: "1 tsp", isOptional: false },
      { name: "olive oil", quantity: "4 tbsp", isOptional: false },
      { name: "bread", quantity: "2 slices", isOptional: true },
    ],
  },
  {
    title: "Creamy Pork Tenderloin",
    description: "Pan-roasted pork tenderloin in a creamy mustard and cream sauce.",
    cuisine: "french",
    mealType: "dinner",
    cookTimeMinutes: 35,
    servings: 4,
    dietaryTags: ["gluten-free"],
    instructions: [
      { step_number: 1, text: "Sear seasoned pork on all sides in oil until golden, 8 minutes total." },
      { step_number: 2, text: "Roast in oven at 190°C for 12 minutes." },
      { step_number: 3, text: "Make sauce: sauté garlic in the pan, add white wine and reduce. Add cream and dijon mustard." },
      { step_number: 4, text: "Slice rested pork and serve with sauce." },
    ],
    ingredients: [
      { name: "pork tenderloin", quantity: "600g", isOptional: false },
      { name: "heavy cream", quantity: "200ml", isOptional: false },
      { name: "dijon mustard", quantity: "2 tbsp", isOptional: false },
      { name: "white wine", quantity: "100ml", isOptional: false },
      { name: "garlic", quantity: "3 cloves", isOptional: false },
      { name: "butter", quantity: "2 tbsp", isOptional: false },
      { name: "thyme", quantity: "4 sprigs", isOptional: false },
    ],
  },
  {
    title: "French Onion Soup",
    description: "Classic rich French soup with caramelized onions and gruyère croutons.",
    cuisine: "french",
    mealType: "lunch",
    cookTimeMinutes: 60,
    servings: 4,
    dietaryTags: [],
    instructions: [
      { step_number: 1, text: "Slowly caramelize sliced onions in butter for 30-40 minutes until deeply golden." },
      { step_number: 2, text: "Add white wine and reduce. Add beef broth and thyme. Simmer 15 minutes." },
      { step_number: 3, text: "Ladle into oven-proof bowls. Top with toasted bread and cheese." },
      { step_number: 4, text: "Broil until cheese is bubbly and golden." },
    ],
    ingredients: [
      { name: "onion", quantity: "6 large", isOptional: false },
      { name: "butter", quantity: "3 tbsp", isOptional: false },
      { name: "beef broth", quantity: "1.5L", isOptional: false },
      { name: "white wine", quantity: "200ml", isOptional: false },
      { name: "bread", quantity: "4 slices", isOptional: false },
      { name: "mozzarella cheese", quantity: "200g", isOptional: false },
      { name: "thyme", quantity: "2 sprigs", isOptional: false },
    ],
  },
  {
    title: "Scrambled Eggs & Toast",
    description: "Soft and creamy scrambled eggs on buttery toast — a breakfast staple.",
    cuisine: "american",
    mealType: "breakfast",
    cookTimeMinutes: 8,
    servings: 2,
    dietaryTags: ["vegetarian"],
    instructions: [
      { step_number: 1, text: "Whisk eggs with a splash of milk, salt, and pepper." },
      { step_number: 2, text: "Cook in a buttered pan on low heat, gently folding with a spatula until just set." },
      { step_number: 3, text: "Serve immediately on toasted bread." },
    ],
    ingredients: [
      { name: "eggs", quantity: "4", isOptional: false },
      { name: "milk", quantity: "2 tbsp", isOptional: false },
      { name: "butter", quantity: "1 tbsp", isOptional: false },
      { name: "bread", quantity: "2 slices", isOptional: false },
    ],
  },
  {
    title: "Tuna Nicoise Salad",
    description: "Elegant French salad with tuna, olives, green beans, and a Dijon dressing.",
    cuisine: "french",
    mealType: "lunch",
    cookTimeMinutes: 20,
    servings: 4,
    dietaryTags: ["dairy-free", "gluten-free"],
    instructions: [
      { step_number: 1, text: "Boil potatoes and eggs. Hard-boil eggs for 10 minutes." },
      { step_number: 2, text: "Blanch green beans in boiling water for 3 minutes." },
      { step_number: 3, text: "Whisk olive oil, vinegar, dijon mustard, and garlic for dressing." },
      { step_number: 4, text: "Arrange tuna, potatoes, eggs, green beans, and tomatoes. Drizzle with dressing." },
    ],
    ingredients: [
      { name: "tuna", quantity: "2 cans", isOptional: false },
      { name: "eggs", quantity: "4", isOptional: false },
      { name: "potato", quantity: "4 small", isOptional: false },
      { name: "tomato", quantity: "2", isOptional: false },
      { name: "olive oil", quantity: "4 tbsp", isOptional: false },
      { name: "vinegar", quantity: "2 tbsp", isOptional: false },
      { name: "dijon mustard", quantity: "1 tsp", isOptional: false },
      { name: "garlic", quantity: "1 clove", isOptional: false },
      { name: "capers", quantity: "1 tbsp", isOptional: true },
    ],
  },
  {
    title: "Spicy Jalapeño Cornbread",
    description: "Moist, golden cornbread with pockets of jalapeño and cheddar.",
    cuisine: "american",
    mealType: "snack",
    cookTimeMinutes: 25,
    servings: 8,
    dietaryTags: ["vegetarian"],
    instructions: [
      { step_number: 1, text: "Mix flour, cornmeal, baking powder, sugar, and salt." },
      { step_number: 2, text: "Whisk together egg, milk, and melted butter." },
      { step_number: 3, text: "Combine wet and dry. Fold in diced jalapeño and cheddar." },
      { step_number: 4, text: "Pour into greased pan and bake at 200°C for 20-25 minutes." },
    ],
    ingredients: [
      { name: "flour", quantity: "1 cup", isOptional: false },
      { name: "eggs", quantity: "2", isOptional: false },
      { name: "milk", quantity: "1 cup", isOptional: false },
      { name: "butter", quantity: "4 tbsp", isOptional: false },
      { name: "cheddar cheese", quantity: "100g", isOptional: false },
      { name: "jalapeño", quantity: "2", isOptional: false },
      { name: "baking powder", quantity: "1 tsp", isOptional: false },
      { name: "sugar", quantity: "2 tbsp", isOptional: false },
      { name: "salt", quantity: "1 tsp", isOptional: false },
    ],
  },
  {
    title: "Teriyaki Salmon",
    description: "Glazed salmon with a sweet and savory teriyaki sauce, served over rice.",
    cuisine: "asian",
    mealType: "dinner",
    cookTimeMinutes: 20,
    servings: 4,
    dietaryTags: ["gluten-free", "dairy-free"],
    instructions: [
      { step_number: 1, text: "Mix soy sauce, honey, garlic, and ginger for teriyaki glaze." },
      { step_number: 2, text: "Pan-sear salmon 3 minutes per side." },
      { step_number: 3, text: "Pour glaze over salmon and cook 2 more minutes until sticky." },
      { step_number: 4, text: "Serve over rice with sesame seeds." },
    ],
    ingredients: [
      { name: "salmon fillet", quantity: "4 fillets", isOptional: false },
      { name: "soy sauce", quantity: "4 tbsp", isOptional: false },
      { name: "honey", quantity: "2 tbsp", isOptional: false },
      { name: "garlic", quantity: "3 cloves", isOptional: false },
      { name: "ginger", quantity: "1 inch", isOptional: false },
      { name: "rice", quantity: "2 cups", isOptional: false },
      { name: "sesame oil", quantity: "1 tsp", isOptional: true },
    ],
  },
  {
    title: "Spanakopita (Spinach Pie)",
    description: "Crispy phyllo pastry filled with spinach and feta cheese.",
    cuisine: "mediterranean",
    mealType: "lunch",
    cookTimeMinutes: 45,
    servings: 6,
    dietaryTags: ["vegetarian"],
    instructions: [
      { step_number: 1, text: "Sauté onion and garlic. Add spinach and cook until wilted. Cool." },
      { step_number: 2, text: "Mix cooled spinach with eggs and crumbled feta." },
      { step_number: 3, text: "Layer buttered phyllo sheets in a pan, add filling, top with more phyllo." },
      { step_number: 4, text: "Brush with butter and bake at 180°C for 30 minutes until golden." },
    ],
    ingredients: [
      { name: "spinach", quantity: "500g", isOptional: false },
      { name: "eggs", quantity: "3", isOptional: false },
      { name: "mozzarella cheese", quantity: "300g feta", isOptional: false },
      { name: "onion", quantity: "1", isOptional: false },
      { name: "garlic", quantity: "2 cloves", isOptional: false },
      { name: "butter", quantity: "100g", isOptional: false },
      { name: "flour", quantity: "8 phyllo sheets", isOptional: false },
    ],
  },
  {
    title: "Simple Fried Rice",
    description: "Classic egg fried rice with garlic — great for using up leftover rice.",
    cuisine: "asian",
    mealType: "lunch",
    cookTimeMinutes: 12,
    servings: 2,
    dietaryTags: ["vegetarian", "dairy-free"],
    instructions: [
      { step_number: 1, text: "Heat oil in a wok over high heat. Fry garlic 30 seconds." },
      { step_number: 2, text: "Add cold leftover rice. Break up clumps and stir fry 3 minutes." },
      { step_number: 3, text: "Push rice to side. Scramble eggs. Mix together." },
      { step_number: 4, text: "Season with soy sauce and sesame oil." },
    ],
    ingredients: [
      { name: "rice", quantity: "3 cups cooked", isOptional: false },
      { name: "eggs", quantity: "2", isOptional: false },
      { name: "garlic", quantity: "3 cloves", isOptional: false },
      { name: "soy sauce", quantity: "2 tbsp", isOptional: false },
      { name: "vegetable oil", quantity: "2 tbsp", isOptional: false },
      { name: "sesame oil", quantity: "1 tsp", isOptional: true },
    ],
  },
  {
    title: "Chocolate Mug Cake",
    description: "Quick 5-minute chocolate cake made in the microwave — perfect for a sweet fix.",
    cuisine: "american",
    mealType: "snack",
    cookTimeMinutes: 5,
    servings: 1,
    dietaryTags: ["vegetarian"],
    instructions: [
      { step_number: 1, text: "Mix flour, sugar, cocoa powder, and baking powder in a mug." },
      { step_number: 2, text: "Add egg, milk, melted butter, and vanilla. Mix until smooth." },
      { step_number: 3, text: "Microwave on high for 90 seconds. Let stand 1 minute before eating." },
    ],
    ingredients: [
      { name: "flour", quantity: "4 tbsp", isOptional: false },
      { name: "sugar", quantity: "4 tbsp", isOptional: false },
      { name: "eggs", quantity: "1", isOptional: false },
      { name: "milk", quantity: "3 tbsp", isOptional: false },
      { name: "butter", quantity: "3 tbsp", isOptional: false },
      { name: "vanilla extract", quantity: "1/2 tsp", isOptional: false },
      { name: "baking powder", quantity: "1/4 tsp", isOptional: false },
    ],
  },
  {
    title: "Caprese Salad",
    description: "Classic Italian salad with fresh mozzarella, tomatoes, and basil.",
    cuisine: "italian",
    mealType: "lunch",
    cookTimeMinutes: 5,
    servings: 4,
    dietaryTags: ["vegetarian", "gluten-free"],
    instructions: [
      { step_number: 1, text: "Slice tomatoes and mozzarella into thick rounds." },
      { step_number: 2, text: "Arrange alternating slices on a plate." },
      { step_number: 3, text: "Scatter fresh basil leaves. Drizzle with olive oil and balsamic vinegar. Season." },
    ],
    ingredients: [
      { name: "tomato", quantity: "4", isOptional: false },
      { name: "mozzarella cheese", quantity: "400g", isOptional: false },
      { name: "basil", quantity: "large bunch", isOptional: false },
      { name: "olive oil", quantity: "3 tbsp", isOptional: false },
      { name: "vinegar", quantity: "balsamic, 2 tbsp", isOptional: true },
    ],
  },
  {
    title: "Spiced Roast Chicken",
    description: "Perfectly roasted whole chicken with paprika and herb butter under the skin.",
    cuisine: "american",
    mealType: "dinner",
    cookTimeMinutes: 80,
    servings: 6,
    dietaryTags: ["gluten-free"],
    instructions: [
      { step_number: 1, text: "Mix softened butter with paprika, garlic, thyme, salt, and pepper." },
      { step_number: 2, text: "Loosen skin of the chicken and spread butter mixture underneath." },
      { step_number: 3, text: "Stuff cavity with lemon and garlic. Truss if desired." },
      { step_number: 4, text: "Roast at 200°C for 70-80 minutes until juices run clear. Rest 15 minutes." },
    ],
    ingredients: [
      { name: "chicken thighs", quantity: "1.5kg whole chicken", isOptional: false },
      { name: "butter", quantity: "80g", isOptional: false },
      { name: "paprika", quantity: "2 tsp", isOptional: false },
      { name: "garlic", quantity: "6 cloves", isOptional: false },
      { name: "lemon", quantity: "1", isOptional: false },
      { name: "thyme", quantity: "4 sprigs", isOptional: false },
      { name: "smoked paprika", quantity: "1 tsp", isOptional: true },
    ],
  },
  {
    title: "Zucchini Fritters",
    description: "Crispy pan-fried zucchini fritters with yogurt dipping sauce.",
    cuisine: "mediterranean",
    mealType: "snack",
    cookTimeMinutes: 20,
    servings: 4,
    dietaryTags: ["vegetarian"],
    instructions: [
      { step_number: 1, text: "Grate zucchini and squeeze out excess moisture with a towel." },
      { step_number: 2, text: "Mix with eggs, flour, garlic, parmesan, salt, and pepper." },
      { step_number: 3, text: "Fry spoonfuls in olive oil until golden, 3 minutes per side." },
      { step_number: 4, text: "Serve with yogurt dip." },
    ],
    ingredients: [
      { name: "zucchini", quantity: "3", isOptional: false },
      { name: "eggs", quantity: "2", isOptional: false },
      { name: "flour", quantity: "3 tbsp", isOptional: false },
      { name: "parmesan cheese", quantity: "40g", isOptional: false },
      { name: "garlic", quantity: "2 cloves", isOptional: false },
      { name: "olive oil", quantity: "3 tbsp", isOptional: false },
      { name: "yogurt", quantity: "to serve", isOptional: true },
    ],
  },
  {
    title: "Chicken Noodle Soup",
    description: "Comforting classic chicken noodle soup with vegetables and herbs.",
    cuisine: "american",
    mealType: "lunch",
    cookTimeMinutes: 40,
    servings: 6,
    dietaryTags: ["dairy-free"],
    instructions: [
      { step_number: 1, text: "Cook diced chicken in oil. Remove and set aside." },
      { step_number: 2, text: "Sauté onion, carrot, and celery until soft." },
      { step_number: 3, text: "Add chicken broth and bring to a boil." },
      { step_number: 4, text: "Add noodles and chicken. Cook until noodles are tender, 8-10 minutes." },
      { step_number: 5, text: "Season with salt, pepper, and thyme." },
    ],
    ingredients: [
      { name: "chicken breast", quantity: "400g", isOptional: false },
      { name: "noodles", quantity: "200g egg noodles", isOptional: false },
      { name: "carrot", quantity: "3", isOptional: false },
      { name: "celery", quantity: "3 stalks", isOptional: false },
      { name: "onion", quantity: "1", isOptional: false },
      { name: "chicken broth", quantity: "1.5L", isOptional: false },
      { name: "thyme", quantity: "2 sprigs", isOptional: false },
    ],
  },
  {
    title: "Bruschetta",
    description: "Classic Italian toasted bread with fresh tomatoes, garlic, and basil.",
    cuisine: "italian",
    mealType: "snack",
    cookTimeMinutes: 10,
    servings: 4,
    dietaryTags: ["vegetarian", "vegan"],
    instructions: [
      { step_number: 1, text: "Dice tomatoes and mix with garlic, basil, olive oil, and vinegar." },
      { step_number: 2, text: "Season with salt and let sit 10 minutes." },
      { step_number: 3, text: "Toast bread until golden. Rub each slice with a raw garlic clove." },
      { step_number: 4, text: "Top with tomato mixture and serve immediately." },
    ],
    ingredients: [
      { name: "tomato", quantity: "4", isOptional: false },
      { name: "bread", quantity: "8 slices", isOptional: false },
      { name: "garlic", quantity: "3 cloves", isOptional: false },
      { name: "basil", quantity: "fresh bunch", isOptional: false },
      { name: "olive oil", quantity: "4 tbsp", isOptional: false },
      { name: "vinegar", quantity: "1 tbsp", isOptional: true },
    ],
  },
  {
    title: "Paneer Tikka Masala",
    description: "Creamy tomato-based curry with paneer — the vegetarian answer to butter chicken.",
    cuisine: "indian",
    mealType: "dinner",
    cookTimeMinutes: 35,
    servings: 4,
    dietaryTags: ["vegetarian", "gluten-free"],
    instructions: [
      { step_number: 1, text: "Cut paneer into cubes and pan-fry until golden on each side." },
      { step_number: 2, text: "Sauté onion, garlic, and ginger. Add curry powder and cumin." },
      { step_number: 3, text: "Add tomato sauce and simmer 10 minutes." },
      { step_number: 4, text: "Add cream and paneer. Simmer 5 minutes. Serve with rice." },
    ],
    ingredients: [
      { name: "mozzarella cheese", quantity: "400g paneer", isOptional: false },
      { name: "tomato sauce", quantity: "400ml", isOptional: false },
      { name: "heavy cream", quantity: "100ml", isOptional: false },
      { name: "onion", quantity: "1", isOptional: false },
      { name: "garlic", quantity: "4 cloves", isOptional: false },
      { name: "ginger", quantity: "1 inch", isOptional: false },
      { name: "curry powder", quantity: "2 tbsp", isOptional: false },
      { name: "cumin", quantity: "1 tsp", isOptional: false },
      { name: "butter", quantity: "2 tbsp", isOptional: false },
    ],
  },
  {
    title: "Spanish Omelette (Tortilla)",
    description: "Classic Spanish potato and egg omelette — delicious hot or at room temperature.",
    cuisine: "mediterranean",
    mealType: "breakfast",
    cookTimeMinutes: 40,
    servings: 6,
    dietaryTags: ["vegetarian", "gluten-free", "dairy-free"],
    instructions: [
      { step_number: 1, text: "Slice potatoes and onion thinly. Cook slowly in olive oil 20 minutes." },
      { step_number: 2, text: "Whisk 6 eggs. Season well. Add cooled potato mixture." },
      { step_number: 3, text: "Cook in an oiled pan over medium heat 5 minutes until set on bottom." },
      { step_number: 4, text: "Flip onto a plate, then slide back into pan to cook the other side." },
    ],
    ingredients: [
      { name: "eggs", quantity: "6", isOptional: false },
      { name: "potato", quantity: "3", isOptional: false },
      { name: "onion", quantity: "1", isOptional: false },
      { name: "olive oil", quantity: "5 tbsp", isOptional: false },
      { name: "salt", quantity: "to taste", isOptional: false },
    ],
  },
  {
    title: "Roasted Broccoli with Garlic",
    description: "Crispy roasted broccoli with garlic and lemon — a perfect simple side dish.",
    cuisine: "american",
    mealType: "lunch",
    cookTimeMinutes: 20,
    servings: 4,
    dietaryTags: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
    instructions: [
      { step_number: 1, text: "Cut broccoli into florets. Toss with olive oil, garlic, salt, and pepper." },
      { step_number: 2, text: "Roast at 210°C for 15-20 minutes until crispy and charred at edges." },
      { step_number: 3, text: "Finish with a squeeze of lemon juice." },
    ],
    ingredients: [
      { name: "broccoli", quantity: "1 large head", isOptional: false },
      { name: "garlic", quantity: "4 cloves", isOptional: false },
      { name: "olive oil", quantity: "3 tbsp", isOptional: false },
      { name: "lemon", quantity: "1/2", isOptional: false },
      { name: "red pepper flakes", quantity: "pinch", isOptional: true },
    ],
  },
  {
    title: "French Toast",
    description: "Golden eggy French toast dusted with cinnamon and served with maple syrup.",
    cuisine: "french",
    mealType: "breakfast",
    cookTimeMinutes: 15,
    servings: 4,
    dietaryTags: ["vegetarian"],
    instructions: [
      { step_number: 1, text: "Whisk eggs, milk, cinnamon, and vanilla together." },
      { step_number: 2, text: "Dip bread slices in the egg mixture, letting them soak 30 seconds each side." },
      { step_number: 3, text: "Fry in buttered pan over medium heat until golden, 2-3 minutes per side." },
      { step_number: 4, text: "Serve with honey or powdered sugar." },
    ],
    ingredients: [
      { name: "bread", quantity: "4 thick slices", isOptional: false },
      { name: "eggs", quantity: "3", isOptional: false },
      { name: "milk", quantity: "1/2 cup", isOptional: false },
      { name: "butter", quantity: "2 tbsp", isOptional: false },
      { name: "cinnamon", quantity: "1 tsp", isOptional: false },
      { name: "vanilla extract", quantity: "1 tsp", isOptional: false },
      { name: "honey", quantity: "to serve", isOptional: true },
    ],
  },
  {
    title: "Smashed Cucumber Salad",
    description: "Refreshing Chinese-style smashed cucumber salad with garlic and chili oil.",
    cuisine: "asian",
    mealType: "lunch",
    cookTimeMinutes: 10,
    servings: 4,
    dietaryTags: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
    instructions: [
      { step_number: 1, text: "Smash cucumbers with the flat of a knife. Cut into pieces." },
      { step_number: 2, text: "Sprinkle with salt and let sit 10 minutes. Drain excess water." },
      { step_number: 3, text: "Dress with garlic, soy sauce, vinegar, sesame oil, and sugar." },
      { step_number: 4, text: "Toss and serve." },
    ],
    ingredients: [
      { name: "cucumber", quantity: "2 large", isOptional: false },
      { name: "garlic", quantity: "3 cloves", isOptional: false },
      { name: "soy sauce", quantity: "2 tbsp", isOptional: false },
      { name: "vinegar", quantity: "1 tbsp rice vinegar", isOptional: false },
      { name: "sesame oil", quantity: "1 tbsp", isOptional: false },
      { name: "sugar", quantity: "1 tsp", isOptional: false },
      { name: "red pepper flakes", quantity: "to taste", isOptional: true },
    ],
  },
  {
    title: "Baked Mac and Cheese",
    description: "Creamy, golden baked macaroni and cheese with a crunchy breadcrumb topping.",
    cuisine: "american",
    mealType: "dinner",
    cookTimeMinutes: 40,
    servings: 6,
    dietaryTags: ["vegetarian"],
    instructions: [
      { step_number: 1, text: "Cook pasta. Make a roux with butter and flour. Gradually whisk in milk." },
      { step_number: 2, text: "Stir in cheddar and a touch of mustard until melted." },
      { step_number: 3, text: "Combine sauce with pasta. Pour into baking dish." },
      { step_number: 4, text: "Top with panko breadcrumbs. Bake at 190°C for 20-25 minutes." },
    ],
    ingredients: [
      { name: "pasta", quantity: "400g macaroni", isOptional: false },
      { name: "cheddar cheese", quantity: "300g", isOptional: false },
      { name: "milk", quantity: "500ml", isOptional: false },
      { name: "butter", quantity: "4 tbsp", isOptional: false },
      { name: "flour", quantity: "3 tbsp", isOptional: false },
      { name: "dijon mustard", quantity: "1 tsp", isOptional: false },
      { name: "panko breadcrumbs", quantity: "60g", isOptional: false },
    ],
  },
];

async function main() {
  console.log("🌱 Seeding database...");

  // Upsert all ingredients
  const ingredientMap: Record<string, string> = {};
  for (const ing of ingredients) {
    const result = await prisma.ingredient.upsert({
      where: { name: ing.name },
      update: { category: ing.category },
      create: { name: ing.name, category: ing.category },
    });
    ingredientMap[ing.name] = result.id;
  }
  console.log(`✓ ${Object.keys(ingredientMap).length} ingredients created`);

  // Collect all recipe ingredient names to ensure they exist
  const allRecipeIngNames = new Set<string>();
  for (const recipe of recipes) {
    for (const ri of recipe.ingredients) {
      allRecipeIngNames.add(ri.name);
    }
  }

  for (const name of allRecipeIngNames) {
    if (!ingredientMap[name]) {
      const result = await prisma.ingredient.upsert({
        where: { name },
        update: {},
        create: { name, category: "other" },
      });
      ingredientMap[name] = result.id;
    }
  }

  // Create recipes
  let recipeCount = 0;
  for (const recipe of recipes) {
    const existing = await prisma.recipe.findFirst({
      where: { title: recipe.title },
    });
    if (existing) continue;

    await prisma.recipe.create({
      data: {
        title: recipe.title,
        description: recipe.description,
        cuisine: recipe.cuisine,
        mealType: recipe.mealType,
        cookTimeMinutes: recipe.cookTimeMinutes,
        servings: recipe.servings,
        dietaryTags: recipe.dietaryTags,
        instructions: recipe.instructions,
        recipeIngredients: {
          create: recipe.ingredients.map((ri) => ({
            ingredientId: ingredientMap[ri.name],
            quantity: ri.quantity,
            isOptional: ri.isOptional,
          })),
        },
      },
    });
    recipeCount++;
  }

  console.log(`✓ ${recipeCount} recipes created`);
  console.log("✅ Seed complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
